/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Main;

import Controller.Autenticacao;
import Controller.CarregarListas;
import Controller.LoadList;
import Controller.Manager;
import Controller.SalvarListas;
import Controller.SaveList;
import Model.Candidato;
import Model.Eleitor;
import View.TelaMenu;
import java.util.ArrayList;
import java.util.List;

public class App {
    public static void main(String[] args) {
        LoadList carregar = new CarregarListas();
        List<Candidato> candidatos = carregar.carregarTxtCandidatos();
        List<Eleitor> eleitores = carregar.carregarTxtEleitores();
       
        Autenticacao auth = new Autenticacao(eleitores);
        Manager manager = new Manager(candidatos, eleitores, auth);
        SaveList savelist = new SalvarListas(eleitores, candidatos);
        
        TelaMenu telaMenu = new TelaMenu(manager, savelist);
        telaMenu.setVisible(true);
       
        
    }
}
